"""init libros

Revision ID: aed8e48a7ff8
Revises: 
Create Date: 2025-12-29 19:05:32.471397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed8e48a7ff8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('autor', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_libros_autor'), 'libros', ['autor'], unique=False)
    op.create_index(op.f('ix_libros_id'), 'libros', ['id'], unique=False)
    op.create_index(op.f('ix_libros_titulo'), 'libros', ['titulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_libros_titulo'), table_name='libros')
    op.drop_index(op.f('ix_libros_id'), table_name='libros')
    op.drop_index(op.f('ix_libros_autor'), table_name='libros')
    op.drop_table('libros')
    # ### end Alembic commands ###
